### ISSUE TITLE
Comprobar que no se puedan crear cuentas con el mismo correo

### ISSUE THREAD

**Issue by electrototo** [electrototo/chapterchicks#11]
El correo debe ser único, dos usuarios distintos no pueden tener el mismo correo electrónico, porque si lo tienen pueden empezar a introducir bugs en el programa

**Comment by lennygin** [comment]
eso se puede hacer con un stringcompare???

**Comment by electrototo** [comment]
así es

**Comment by electrototo** [comment]
- [ ] En la creación de un usuario administrador
- [ ] En la creación de cualquier usuario

**Comment by electrototo** [comment]
Se solventó con la creación de una función que agrega usuarios al sistema
